fix: ensure user is authorized before calling codeartifact_login and handle status code != 0 (#250)

diff --git a/dev-tools-mock/codeartifact-login b/dev-tools-mock/codeartifact-login
--- a/dev-tools-mock/codeartifact-login
+++ b/dev-tools-mock/codeartifact-login
@@ -1,2 +1,5 @@
 #!/bin/bash
+# export PATH="./wombat/dev-tools-mock/:$PATH"
 aws sts get-caller-identity
+echo "Cannot recover from this trauma." 1>&2;
+exit 1
